<div style="display: flex; justify-content: space-between;">
    <div>
        <?php echo $block->getData('message'); ?>
    </div>

    <div>
        <?php if ($block->getData('url')) { ?>
            <a href="<?php echo $block->getData('url'); ?>" target="_blank">
                <button id="downloadDocument"
                        title="Descarregar Documento" type="button" class="action- scalable action-default"
                        style="margin-right: 10px"
                        data-ui-id="addattribute-button">
                <span>
                    <?php echo $block->getData('button_text') ? $block->getData('button_text') : "Ver documento"; ?>
                </span>
                </button>
            </a>
        <?php } ?>

        <?php if ($block->getData('download_url')) { ?>
            <a href="<?php echo $block->getData('download_url'); ?>" target="_blank">
                <button id="viewDocument" title="Ver documento" type="button" class="action- scalable action-default"
                        data-ui-id="addattribute-button">
                <span>
                    Descarregar documento
                </span>
                </button>
            </a>
        <?php } ?>
    </div>
</div>