<form id="form-validate" action="<?php echo $block->getUrl('moloni/settings/index') ?>" method="post">
    <?php echo $block->getBlockHtml('formkey') ?>

    <?php echo $block->getSetting('orders_since'); ?>
    <fieldset class="admin__fieldset">
        <div class="admin__field _required">
            <div class="admin__field-label">
                <label for="GK7UVGQ">
                    <span>Product Name</span>
                </label>
            </div>
            <div class="admin__field-control">
                <input class="admin__control-text" type="text" name="product[name]" aria-describedby="notice-GK7UVGQ"
                       id="GK7UVGQ" maxlength="255">
            </div>
        </div>


        <div class="admin__field">
            <div class="admin__field-label">
                <label for="OY72HLQ">
                    <span>Tax Class</span>
                </label>
            </div>
            <div class="admin__field-control">
                <select class="admin__control-select" name="product[tax_class_id]" id="OY72HLQ"
                        aria-describedby="notice-OY72HLQ">
                    <option data-title="None" value="0">None</option>
                    <option data-title="Taxable Goods" value="2">Taxable Goods</option>
                    <option data-title="Refund Adjustments" value="4">Refund Adjustments</option>
                    <option data-title="Gift Options" value="5">Gift Options</option>
                    <option data-title="Order Gift Wrapping" value="6">Order Gift Wrapping</option>
                    <option data-title="Item Gift Wrapping" value="7">Item Gift Wrapping</option>
                    <option data-title="Printed Gift Card" value="8">Printed Gift Card</option>
                    <option data-title="Reward Points" value="9">Reward Points</option>
                </select>
            </div>
        </div>
    </fieldset>

    <button type="submit" class="action save primary">
        <span><?php echo __('Guardar Alterações') ?></span>
    </button>
</form>
<script>
    require(['jquery', 'mage/mage', 'Invoicing_Moloni/js/datatables.min'], function ($) {
        $('#form-validate').mage('validation', {});
    });
</script>
